apiVersion: v1
kind: Service
metadata:
  name: {{ include "keycloak.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: keycloak
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8443
      name: https
  selector:
    app: keycloak
  type: {{ .Values.service.type }}
